// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/valuation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValuationService_CalculateValuation_FullMethodName = "/valuation.ValuationService/CalculateValuation"
)

// ValuationServiceClient is the client API for ValuationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ValuationService provides methods for property valuation
type ValuationServiceClient interface {
	// CalculateValuation calculates the value of a property
	CalculateValuation(ctx context.Context, in *ValuationRequest, opts ...grpc.CallOption) (*ValuationResponse, error)
}

type valuationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValuationServiceClient(cc grpc.ClientConnInterface) ValuationServiceClient {
	return &valuationServiceClient{cc}
}

func (c *valuationServiceClient) CalculateValuation(ctx context.Context, in *ValuationRequest, opts ...grpc.CallOption) (*ValuationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValuationResponse)
	err := c.cc.Invoke(ctx, ValuationService_CalculateValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValuationServiceServer is the server API for ValuationService service.
// All implementations must embed UnimplementedValuationServiceServer
// for forward compatibility.
//
// ValuationService provides methods for property valuation
type ValuationServiceServer interface {
	// CalculateValuation calculates the value of a property
	CalculateValuation(context.Context, *ValuationRequest) (*ValuationResponse, error)
	mustEmbedUnimplementedValuationServiceServer()
}

// UnimplementedValuationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValuationServiceServer struct{}

func (UnimplementedValuationServiceServer) CalculateValuation(context.Context, *ValuationRequest) (*ValuationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateValuation not implemented")
}
func (UnimplementedValuationServiceServer) mustEmbedUnimplementedValuationServiceServer() {}
func (UnimplementedValuationServiceServer) testEmbeddedByValue()                          {}

// UnsafeValuationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValuationServiceServer will
// result in compilation errors.
type UnsafeValuationServiceServer interface {
	mustEmbedUnimplementedValuationServiceServer()
}

func RegisterValuationServiceServer(s grpc.ServiceRegistrar, srv ValuationServiceServer) {
	// If the following call pancis, it indicates UnimplementedValuationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValuationService_ServiceDesc, srv)
}

func _ValuationService_CalculateValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValuationServiceServer).CalculateValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValuationService_CalculateValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValuationServiceServer).CalculateValuation(ctx, req.(*ValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValuationService_ServiceDesc is the grpc.ServiceDesc for ValuationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValuationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "valuation.ValuationService",
	HandlerType: (*ValuationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateValuation",
			Handler:    _ValuationService_CalculateValuation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/valuation.proto",
}
