// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/valuation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Property represents a real estate property
type Property struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PropertyType     string                 `protobuf:"bytes,2,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	Bedrooms         int32                  `protobuf:"varint,3,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	Bathrooms        int32                  `protobuf:"varint,4,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	SquareFootage    int32                  `protobuf:"varint,5,opt,name=square_footage,json=squareFootage,proto3" json:"square_footage,omitempty"`
	YearBuilt        int32                  `protobuf:"varint,6,opt,name=year_built,json=yearBuilt,proto3" json:"year_built,omitempty"`
	Condition        string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`
	MaintenanceLevel string                 `protobuf:"bytes,8,opt,name=maintenance_level,json=maintenanceLevel,proto3" json:"maintenance_level,omitempty"`
	RenovationStatus string                 `protobuf:"bytes,9,opt,name=renovation_status,json=renovationStatus,proto3" json:"renovation_status,omitempty"`
	Features         []string               `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_proto_valuation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valuation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_proto_valuation_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Property) GetPropertyType() string {
	if x != nil {
		return x.PropertyType
	}
	return ""
}

func (x *Property) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

func (x *Property) GetBathrooms() int32 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *Property) GetSquareFootage() int32 {
	if x != nil {
		return x.SquareFootage
	}
	return 0
}

func (x *Property) GetYearBuilt() int32 {
	if x != nil {
		return x.YearBuilt
	}
	return 0
}

func (x *Property) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Property) GetMaintenanceLevel() string {
	if x != nil {
		return x.MaintenanceLevel
	}
	return ""
}

func (x *Property) GetRenovationStatus() string {
	if x != nil {
		return x.RenovationStatus
	}
	return ""
}

func (x *Property) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// ValuationResult represents the result of a property valuation
type ValuationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Issues        []string               `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuationResult) Reset() {
	*x = ValuationResult{}
	mi := &file_proto_valuation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuationResult) ProtoMessage() {}

func (x *ValuationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valuation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuationResult.ProtoReflect.Descriptor instead.
func (*ValuationResult) Descriptor() ([]byte, []int) {
	return file_proto_valuation_proto_rawDescGZIP(), []int{1}
}

func (x *ValuationResult) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ValuationResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ValuationResult) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ValuationResult) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

// ValuationRequest represents a request to value a property
type ValuationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuationRequest) Reset() {
	*x = ValuationRequest{}
	mi := &file_proto_valuation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuationRequest) ProtoMessage() {}

func (x *ValuationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valuation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuationRequest.ProtoReflect.Descriptor instead.
func (*ValuationRequest) Descriptor() ([]byte, []int) {
	return file_proto_valuation_proto_rawDescGZIP(), []int{2}
}

func (x *ValuationRequest) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

// ValuationResponse represents the response from a valuation request
type ValuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ValuationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuationResponse) Reset() {
	*x = ValuationResponse{}
	mi := &file_proto_valuation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuationResponse) ProtoMessage() {}

func (x *ValuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valuation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuationResponse.ProtoReflect.Descriptor instead.
func (*ValuationResponse) Descriptor() ([]byte, []int) {
	return file_proto_valuation_proto_rawDescGZIP(), []int{3}
}

func (x *ValuationResponse) GetResult() *ValuationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_valuation_proto protoreflect.FileDescriptor

const file_proto_valuation_proto_rawDesc = "" +
	"\n" +
	"\x15proto/valuation.proto\x12\tvaluation\"\xdd\x02\n" +
	"\bProperty\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rproperty_type\x18\x02 \x01(\tR\fpropertyType\x12\x1a\n" +
	"\bbedrooms\x18\x03 \x01(\x05R\bbedrooms\x12\x1c\n" +
	"\tbathrooms\x18\x04 \x01(\x05R\tbathrooms\x12%\n" +
	"\x0esquare_footage\x18\x05 \x01(\x05R\rsquareFootage\x12\x1d\n" +
	"\n" +
	"year_built\x18\x06 \x01(\x05R\tyearBuilt\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12+\n" +
	"\x11maintenance_level\x18\b \x01(\tR\x10maintenanceLevel\x12+\n" +
	"\x11renovation_status\x18\t \x01(\tR\x10renovationStatus\x12\x1a\n" +
	"\bfeatures\x18\n" +
	" \x03(\tR\bfeatures\"\x81\x01\n" +
	"\x0fValuationResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12\x16\n" +
	"\x06issues\x18\x04 \x03(\tR\x06issues\"C\n" +
	"\x10ValuationRequest\x12/\n" +
	"\bproperty\x18\x01 \x01(\v2\x13.valuation.PropertyR\bproperty\"G\n" +
	"\x11ValuationResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.valuation.ValuationResultR\x06result2e\n" +
	"\x10ValuationService\x12Q\n" +
	"\x12CalculateValuation\x12\x1b.valuation.ValuationRequest\x1a\x1c.valuation.ValuationResponse\"\x00B6Z4github.com/jsarcade/property-valuation-service/protob\x06proto3"

var (
	file_proto_valuation_proto_rawDescOnce sync.Once
	file_proto_valuation_proto_rawDescData []byte
)

func file_proto_valuation_proto_rawDescGZIP() []byte {
	file_proto_valuation_proto_rawDescOnce.Do(func() {
		file_proto_valuation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_valuation_proto_rawDesc), len(file_proto_valuation_proto_rawDesc)))
	})
	return file_proto_valuation_proto_rawDescData
}

var file_proto_valuation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_valuation_proto_goTypes = []any{
	(*Property)(nil),          // 0: valuation.Property
	(*ValuationResult)(nil),   // 1: valuation.ValuationResult
	(*ValuationRequest)(nil),  // 2: valuation.ValuationRequest
	(*ValuationResponse)(nil), // 3: valuation.ValuationResponse
}
var file_proto_valuation_proto_depIdxs = []int32{
	0, // 0: valuation.ValuationRequest.property:type_name -> valuation.Property
	1, // 1: valuation.ValuationResponse.result:type_name -> valuation.ValuationResult
	2, // 2: valuation.ValuationService.CalculateValuation:input_type -> valuation.ValuationRequest
	3, // 3: valuation.ValuationService.CalculateValuation:output_type -> valuation.ValuationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_valuation_proto_init() }
func file_proto_valuation_proto_init() {
	if File_proto_valuation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_valuation_proto_rawDesc), len(file_proto_valuation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_valuation_proto_goTypes,
		DependencyIndexes: file_proto_valuation_proto_depIdxs,
		MessageInfos:      file_proto_valuation_proto_msgTypes,
	}.Build()
	File_proto_valuation_proto = out.File
	file_proto_valuation_proto_goTypes = nil
	file_proto_valuation_proto_depIdxs = nil
}
